name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 18 * * *' # Runs on 6 pm each day
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@niklasvmoers"
